import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import TrainMap from '../components/TrainMap';
import * as d3 from 'd3';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tarasp Booklet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TrainMap />
      </main>
      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
