import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'

const TrainMap = dynamic(() => import('../components/TrainMap'), { ssr: false })

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tarasp Booklet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css" integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ==" crossorigin="" />
        <link rel="stylesheet" type="text/css" href="https://s3-eu-west-1.amazonaws.com/aws-ec2-eu-1-opendatasoft-staticfileset/sbb/stylesheet/26.css"></link>
      </Head>
      <main className={styles.main}>
        {(typeof window !== 'undefined') && <TrainMap />}
      </main>
      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
